main.out: main.o id_000.o id_001.o id_002a.o id_002b.o id_003.o id_004.o id_005.o id_006.o id_007.o id_008.o id_009.o id_010.o student.o
	g++ -g main.o id_000.o id_001.o id_002a.o id_002b.o id_003.o id_004.o id_005.o id_006.o id_007.o id_008.o id_009.o id_010.o student.o

main.o: main.cc
	g++ -g -c main.cc

student.o: classes/student.cc
	g++ -g -c classes/student.cc

id_000.o: id_000/id_000.cc
	g++ -g -c id_000/id_000.cc

id_001.o: id_001/id_001.cc
	g++ -g -c id_001/id_001.cc

id_002a.o: id_002/id_002a.cc
	g++ -g -c id_002/id_002a.cc

id_002b.o: id_002/id_002b.cc
	g++ -g -c id_002/id_002b.cc

id_003.o: id_003/id_003.cc
	g++ -g -c id_003/id_003.cc

id_004.o: id_004/id_004.cc
	g++ -g -c id_004/id_004.cc

id_005.o: id_005/id_005.cc
	g++ -g  -c id_005/id_005.cc

id_006.o: id_006/id_006.cc
	g++ -g -c id_006/id_006.cc

id_007.o: id_007/id_007.cc
	g++ -g -c id_007/id_007.cc

id_008.o: id_008/id_008.cc
	g++ -g -c id_008/id_008.cc

id_009.o: id_009/id_009.cc
	g++ -g -c id_009/id_009.cc

id_010.o: id_010/id_010.cc
	g++ -g -c id_010/id_010.cc
